version: '3'
volumes:
  rabbit-data:
  mongo-data:
services:
  rabbitMq:
    image: rabbitmq:3-management
    ports:
       - "15672:15672"
       - "5672:5672"
       - "5671:5671"
    environment:
      RABBITMQ_DEFAULT_PASS: pass
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_VHOST: vhost
    volumes:
      - rabbit-data:/var/lib/rabbitmq
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongo-data:/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet